Update dependency prettier to v2.8.1 (#886)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`2.4.1` -> `2.8.1`](https://renovatebot.com/diffs/npm/prettier/2.4.1/2.8.1) | [![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.1/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.1/compatibility-slim/2.4.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.1/confidence-slim/2.4.1)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>prettier/prettier</summary>

### [`v2.8.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;281)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.0...2.8.1)

[diff](https://togithub.com/prettier/prettier/compare/2.8.0...2.8.1)

##### Fix SCSS map in arguments ([#&#8203;9184](https://togithub.com/prettier/prettier/pull/9184) by [@&#8203;agamkrbit](https://togithub.com/agamkrbit))

<!-- prettier-ignore -->

```scss
// Input
$display-breakpoints: map-deep-merge(
  (
    "print-only": "only print",
    "screen-only": "only screen",
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, "sm")-1})",
  ),
  $display-breakpoints
);

// Prettier 2.8.0
$display-breakpoints: map-deep-merge(
  (
    "print-only": "only print",
    "screen-only": "only screen",
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, " sm
      ")-1})",
  ),
  $display-breakpoints
);

// Prettier 2.8.1
$display-breakpoints: map-deep-merge(
  (
    "print-only": "only print",
    "screen-only": "only screen",
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, "sm")-1})",
  ),
  $display-breakpoints
);
```

##### Support auto accessors syntax ([#&#8203;13919](https://togithub.com/prettier/prettier/pull/13919) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

Support for [Auto Accessors Syntax](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#auto-accessors-in-classes) landed in TypeScript 4.9.

(Doesn't work well with `babel-ts` parser)

<!-- prettier-ignore -->

```tsx
class Foo {
  accessor foo: number = 3;
}
```

### [`v2.8.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;280)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.7.1...2.8.0)

[diff](https://togithub.com/prettier/prettier/compare/2.7.1...2.8.0)

🔗 [Release Notes](https://prettier.io/blog/2022/11/23/2.8.0.html)

### [`v2.7.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;271)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.7.0...2.7.1)

[diff](https://togithub.com/prettier/prettier/compare/2.7.0...2.7.1)

##### Keep useful empty lines in description ([#&#8203;13013](https://togithub.com/prettier/prettier/pull/13013) by [@&#8203;chimurai](https://togithub.com/chimurai))

<!-- prettier-ignore -->

```graphql
```

### [`v2.7.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#Prettier-270)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.6.2...2.7.0)

"""
First line
Second Line
"""
type Person {
name: String
}

### [`v2.6.2`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;262)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.6.1...2.6.2)

[diff](https://togithub.com/prettier/prettier/compare/2.6.1...2.6.2)

##### Fix LESS/SCSS format error ([#&#8203;12536](https://togithub.com/prettier/prettier/pull/12536) by [@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```less
// Input
.background-gradient(@&#8203;cut) {
    background: linear-gradient(
        to right,
        @&#8203;white 0%,
        @&#8203;white (@&#8203;cut - 0.01%),
        @&#8203;portal-background @&#8203;cut,
        @&#8203;portal-background 100%
    );
}

// Prettier 2.6.1
TypeError: Cannot read properties of undefined (reading 'endOffset')

// Prettier 2.6.2
.background-gradient(@&#8203;cut) {
  background: linear-gradient(
    to right,
    @&#8203;white 0%,
    @&#8203;white (@&#8203;cut - 0.01%),
    @&#8203;portal-background @&#8203;cut,
    @&#8203;portal-background 100%
  );
}
```

##### Update `meriyah` to fix several bugs ([#&#8203;12567](https://togithub.com/prettier/prettier/pull/12567) by [@&#8203;fisker](https://togithub.com/fisker), fixes in [`meriyah`](https://togithub.com/meriyah/meriyah/) by [@&#8203;3cp](https://togithub.com/3cp))

Fixes bugs when parsing following valid code:

```js
foo(await bar());
```

```js
const regex = /.*/ms;
```

```js
const element = <p>{/w/.test(s)}</p>;
```

```js
class A extends B {
  #privateMethod() {
    super.method();
  }
}
```

### [`v2.6.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;261)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.6.0...2.6.1)

[diff](https://togithub.com/prettier/prettier/compare/2.6.0...2.6.1)

##### Ignore `loglevel` when printing information ([#&#8203;12477](https://togithub.com/prettier/prettier/pull/12477) by [@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```bash
```

### [`v2.6.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#Prettier-260)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.5.1...2.6.0)

prettier --loglevel silent --find-config-path index.js

### [`v2.5.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;251)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.5.0...2.5.1)

[diff](https://togithub.com/prettier/prettier/compare/2.5.0...2.5.1)

##### Improve formatting for empty tuple types ([#&#8203;11884](https://togithub.com/prettier/prettier/pull/11884) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

<!-- prettier-ignore -->

```tsx
// Input
type Foo =
  Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends []
    ? Foo3
    : Foo4;

// Prettier 2.5.0
type Foo = Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends [

]
  ? Foo3
  : Foo4;

// Prettier 2.5.0 (tailingCommma = all)
// Invalid TypeScript code
type Foo = Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends [
  ,
]
  ? Foo3
  : Foo4;

// Prettier 2.5.1
type Foo =
  Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends []
    ? Foo3
    : Foo4;

```

##### Fix compatibility with Jest inline snapshot test ([#&#8203;11892](https://togithub.com/prettier/prettier/pull/11892) by [@&#8203;fisker](https://togithub.com/fisker))

A internal change in Prettier@v2.5.0 accidentally breaks the Jest inline snapshot test.

##### Support Glimmer's named blocks ([#&#8203;11899](https://togithub.com/prettier/prettier/pull/11899) by [@&#8203;duailibe](https://togithub.com/duailibe))

Prettier already supported this feature, but it converted empty named blocks to self-closing, which is not supported by the Glimmer compiler.

See: [Glimmer's named blocks](https://emberjs.github.io/rfcs/0460-yieldable-named-blocks.html).

<!-- prettier-ignore -->

```hbs
// Input
<Component>
  <:named></:named>
</Component>

// Prettier 2.5.0
<Component>
  <:named />
</Component>

// Prettier 2.5.1
<Component>
  <:named></:named>
</Component>
```

### [`v2.5.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;250)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.4.1...2.5.0)

[diff](https://togithub.com/prettier/prettier/compare/2.4.1...2.5.0)

🔗 [Release Notes](https://prettier.io/blog/2021/11/25/2.5.0.html)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://app.renovatebot.com/dashboard#github/ttbud/ttbud).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNC41MS4wIiwidXBkYXRlZEluVmVyIjoiMzQuNTEuMCJ9-->